import:
  #- ~/.config/alacritty/themes/themes/ayu_dark.yaml
 - ~/.config/alacritty/themes/themes/ayu_dark.yaml

font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

  size: 14
  offset:
    x: 0
    y: 5
  glyph_offset:
    x: 0
    y: 3
      #  use_thin_strokes: true

draw_bold_text_with_bright_colors: true
