env:
  TERM: xterm-256color
  #  TERM: alacritty

draw_bold_text_with_bright_colors: true
custom_cursor_colors: true

font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

  size: 14
  offset:
    x: 0
    y: 5
  glyph_offset:
    x: 0
    y: 3
    #  use_thin_strokes: true

bell:
  duration: 500 # visual bell for alerts

mouse:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

dynamic_title: true

shell:
  program: /opt/homebrew/bin/zsh # Use the Brew installation of ZSH
  args:
    - --login

key_bindings:
- { key: N, mods: Command, action: CreateNewWindow }


  #colors:

import:
  #    - ~/.config/alacritty/themes/themes/ayu_dark.yaml 
  #  - ~/.config/alacritty/themes/themes/ayu_mirage.yaml
  #  - ~/.config/alacritty/themes/themes/frank_mirage.yaml
  #   - ~/.config/alacritty/themes/themes/one_dark.yaml
       - ~/.config/alacritty/themes/themes/solarized-dark.yaml
  #       - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml
  #   - ~/.config/alacritty/themes/themes/afterglow.yaml

