# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

right_format = """$kubernetes"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
style = "blue"

[character]
success_symbol = "[❯](bright purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-black"
truncation_length=28

[git_status]
format = " [[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "≡"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# kubernetes
[kubernetes]
format = '[$symbol$context( | $namespace)]($style)'
symbol = ""
style = "dimmed green"
disabled = false

[kubernetes.context_aliases]
"(?P<var_cluster>[\\w-]+).oqton.ai" = "$var_cluster"
"(?P<var_cluster>[\\w-]+).oqton.com.cn" = "$var_cluster"



# single line prompt?
[line_break]
disabled = true

